# Header
menu:
  主页: /
  文章: /archives
#rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true
mathjax: true

# Sidebar
sidebar: right
widgets:
- archive
- recent_posts
- links
#- category
#- tag
- tagcloud

# Links
links:
  yejinru: http://yejinru.com/
  didihe1988: http://didihe1988.github.io/
  nanshu: http://nanshu.me/

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: ay27

# Baidu share
baidushare: false
